config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'

  resources :trucks, except: [:new] do ### BLOG POST
    resources :icecreams
    resources :orders, only: [:new, :create, :index]
  end

  # New Truck
  get 'truck_signup', to: 'trucks#new'

  # New Customer
  get 'signup', to: 'customers#new'
  
  # Sessions
  get 'truck_login', to: "sessions#truck_login"
  post 'truck_login', to: 'sessions#create'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :customers, except: [:new] do
    resources :trucks, only: [:index]
    # Customer Wallet
    get 'wallet', to: 'customers#wallet'
    patch 'wallet', to: 'customers#update_wallet'
  end

  resources :orders, only: [:index]

  # Oauth Facebook
  get '/auth/facebook/callback', to: 'sessions#create_via_fb'

end

app/models/truck.rb
class Truck < ApplicationRecord
    has_many :orders, -> { order(created_at: :desc)}
    has_many :customers, through: :orders
    has_many :icecreams
    validates :name, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    has_secure_password

    scope :in_the_area_of, ->(zipcode) {where("zipcode = ?", zipcode)} 


end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
    before_action :current_customer, only: [:show] # for layout links
    before_action :set_truck, only: [:show]
    before_action :current_truck, only: [:index, :edit, :update]
    before_action :redirect_if_not_logged_in, only: [:index, :show, :edit, :update]

    def new
        redirect_to trucks_path if logged_in?
        session[:user] = "truck"
        @truck = Truck.new
    end

    def create
        @truck = Truck.new(truck_params)
        if @truck.save
            session[:truck_id] = @truck.id
            redirect_to trucks_path
        else
            render :new
        end
    end

    def index
        if session[:user] == "customer"
            redirect_to customer_trucks_path(current_customer) if !check_owner?
            @customer = Customer.find_by(id: params[:customer_id])
            if params[:search_zipcode]
                @trucks = Truck.in_the_area_of(params[:search_zipcode])
            else
                @trucks = Truck.in_the_area_of(@customer.zipcode)
            end
        else
            @trucks = Truck.in_the_area_of(@truck.zipcode)
        end
    end

    def show
        if @truck && params[:flavors] # If a flavor is searched
            @icecreams = Icecream.search_icecreams_by_flavor(params[:flavors][:flavor_name], @truck)
        elsif @truck
            @icecreams = Icecream.where("truck_id = ?", @truck.id)
        else
            redirect_truck_index
        end
    end

    def edit
    end

    def update
        if @truck.update(truck_params)
            redirect_to trucks_path
        else
            render :edit
        end
    end

    private

    def truck_params
        params.require(:truck).permit(:name, :email, :password, :zipcode)
    end

end

app/views/trucks/_flavor_search_form.html.erb
<%= form_tag truck_path(@truck.id), method: :get do %>
    <%= collection_select :flavors, :flavor_name, Flavor.all, :name, :name %>
    <%= submit_tag "Search Flavor" %>
<% end %>

app/views/trucks/_form.html.erb
<%= render partial: "application/errors", locals: {errors: @truck.errors.full_messages.to_sentence}%>

<%= form_for @truck do |f| %>
    <%= f.label "Zipcode: "%><br>
    <%= f.number_field :zipcode %><br>
    <%= f.label "Truck Name: " %><br>
    <%= f.text_field :name %><br>
    <%= f.label "Email: " %><br>
    <%= f.text_field :email %><br>
    <%= f.label "Password: " %><br>
    <%= f.password_field :password %><br>
    <%= f.submit %>
<% end %>

app/views/trucks/_truck.html.erb
<ul>
    <li><strong><%= link_to truck.name, truck_path(truck) %></strong> (<small><i><%= truck.zipcode %></i></small>) </li>
</ul>

app/views/trucks/edit.html.erb
<h1>Edit <%= @truck.name %></h1>

<%= render 'form' %>

app/views/trucks/index.html.erb
<% if session[:truck_id] %>
  <h1> Hello, <%= @truck.name %></h1>

<div class="update-zipcode">
  <% if @truck.zipcode.nil? %>
    <p> <%= link_to "Update your zipcode", edit_truck_path(@truck) %></p>
  <% end %>
</div>

<% else session[:customer_id] %>
  <h1>Welcome <%= @customer.name %></h1>

  <%= form_tag customer_trucks_path(@customer), method: :get do %>
  <%= number_field_tag "search_zipcode" %>
  <%= submit_tag "Search" %>
<% end %>

  <div class="update-zipcode">
  <% if @customer.zipcode.nil? %>
    <p> <%= link_to "Update your zipcode", edit_customer_path(@customer) %></p>
  <% end %>
</div>
<% end %>
<h3> Icecream trucks in your area </h3>

<%= render(@trucks) || "There is no trucks in your area" %>

app/views/trucks/new.html.erb
<h1>Icecream Truck Sign Up</h1>

<%= render 'form' %>

<%= render partial: 'application/facebook', locals: {task: "Sign Up"} %>

app/views/trucks/show.html.erb
<h1><%= @truck.name %>'s Menu </h1>

<%= render 'flavor_search_form' %>

<%= render(@icecreams) || "This icecream truck does not have a menu" %>


<% if check_owner? && session[:truck_id]     %>
<div class="menu-button">
    <strong><%= link_to "Add New Icecream", new_truck_icecream_path(@truck) %></strong>
    </div>
<% elsif session[:customer_id] %>
<div class="menu-button">
    <strong><%= link_to "Start Order", new_truck_order_path(@truck) %></strong>
    </div>
<% end %>