config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'

  resources :trucks, except: [:new] do ### BLOG POST
    resources :icecreams
    resources :orders, only: [:new, :create, :index]
  end

  # New Truck
  get 'truck_signup', to: 'trucks#new'

  # New Customer
  get 'signup', to: 'customers#new'
  
  # Sessions
  get 'truck_login', to: "sessions#truck_login"
  post 'truck_login', to: 'sessions#create'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :customers, except: [:new] do
    resources :trucks, only: [:index]
    # Customer Wallet
    get 'wallet', to: 'customers#wallet'
    patch 'wallet', to: 'customers#update_wallet'
  end

  resources :orders, only: [:index]

  # Oauth Facebook
  get '/auth/facebook/callback', to: 'sessions#create_via_fb'

end

app/models/icecream.rb
class Icecream < ApplicationRecord
    belongs_to :truck
    has_many :icecreams_orders
    has_many :orders, through: :icecreams_orders
    has_and_belongs_to_many :flavors
    validates :name, uniqueness: { scope: :truck_id, message: "already exists on your menu"}, presence: true
    validates :price,presence: true
    validate :flavor_check?
    after_destroy :cancel_orders_upon_delete

    def flavors_attributes=(attributes) # BLOG POST NESTED ATTRIBUTES
        attributes.values.each do |attribute|
            if !attribute[:name].strip.empty?
                flavor = Flavor.find_or_create_by(attribute)
                self.flavors << flavor
            end
            
        end
    end

    def flavors_names
        Flavor.joins(:flavors_icecreams).where("icecream_id = ?", self.id).map {|fl| fl.name}.join(" / ")
    end

    def flavor_check?
        self.errors.add(:flavors,"should exist") if self.flavors.empty?
    end

    private
    
    def cancel_orders_upon_delete # To make sure to Orders of a deleted icecream
        Order.joins(:icecreams_orders).where("icecream_id = ?",self.id).destroy_all
        IcecreamsOrder.where("icecream_id = ?", self.id).destroy_all
    end

    def self.search_icecreams_by_flavor(flavor_name, truck)
        flavor = Flavor.where("name = ?", flavor_name).first
        if flavor_name == "Menu"
            self.where("truck_id = ?", truck.id)
        else
            truck.icecreams.select {|ic| ic.flavor_ids.include?(flavor.id)}
        end
    end

end

app/controllers/icecreams_controller.rb
class IcecreamsController < ApplicationController
    before_action :set_icecream, only: [:show, :edit, :destroy, :update]
    before_action :current_customer, only: [:show, :edit]
    before_action :current_truck
    before_action :redirect_if_not_logged_in
    before_action :all_flavors_except_menu, only: [:new, :create, :edit, :update] # To not show "Menu" as a flavor in checkboxes

    def new
        redirect_to new_truck_icecream_path(@truck) if !check_owner? # Avoids creating new icecreams for other trucks
        @icecream = Icecream.new
    end

    def create
        @icecream = Icecream.new(icecream_params)
        @icecream.truck = @truck
        if @icecream.save
            redirect_to truck_path(@truck)
        else
            render :new
        end
    end
    
    def show
        if !@icecream
            redirect_truck_index
        end
    end

    def edit
        if session[:user] == "truck"
            redirect_to trucks_path, alert: "Sorry. This icecream is not your truck's." if @icecream.truck_id != @truck.id
        else session[:user] == "customer"
            redirect_to customer_trucks_path(@customer), alert: "Only Truck can edit an icecream."
        end
    end

    def update
        if @icecream.update(icecream_params)
            redirect_to truck_path(@truck)
        else
            render :edit
        end
    end

    def destroy
        @icecream.destroy
        redirect_to truck_path(@truck)
    end


    private

    def all_flavors_except_menu
        but_not_menu = Flavor.where("name = ?", "Menu")
        @flavors = Flavor.all - but_not_menu
    end

    def icecream_params
        params.require(:icecream).permit(:name, :price, :flavor_ids => [], flavors_attributes: [:name])
    end

    def set_icecream
        @icecream = Icecream.find_by(id: params[:id])
    end

end

app/views/icecreams/_form.html.erb
<%= form_for @icecream, url: icecream_url(@icecream, @truck) do |f| %>                  <!-- BLOG POST -->
        <%= f.label "Icecream Name: " %><br>
        <%= f.text_field :name %><br>
        <%= f.label "Price" %><br>
        <%= f.text_field :price%><br><br>
        <%= f.collection_check_boxes :flavor_ids, @flavors, :id, :name %>
        <br><br>

    
        <strong>New Flavor</strong>
        <br>
        <%= f.fields_for :flavors, Flavor.new do |flavors_field| %> <!-- BLOG POST nested attributes -->
            <%= flavors_field.label "Flavor Name: " %><br>
            <%= flavors_field.text_field :name %><br>
        <% end %>

        <%= f.submit %>
<% end %>

app/views/icecreams/_icecream.html.erb
<ul>
<li>
    <strong><%= link_to icecream.name, truck_icecream_path(icecream.truck, icecream) %></strong> - $<%= icecream.price %>
    <i><%= icecream.flavors_names %></i>
</li>
</ul>

app/views/icecreams/edit.html.erb
<h1>Edit Icecream</h1>
<%= render partial: "application/errors", locals: {errors: @icecream.errors.full_messages.to_sentence}%>
<%= render 'form' %>

app/views/icecreams/new.html.erb
<h3><%= @truck.name %>'s New Icecream</h3>
<%= render partial: "application/errors", locals: {errors: @icecream.errors.full_messages.to_sentence}%>

<%= render 'form' %>

app/views/icecreams/show.html.erb
<h1><%= @icecream.name %></h1>

<h4>Flavors</h4>

<i><%= @icecream.flavors_names %></i>
<br>

<% if session[:truck_id] && check_owner? %>
    <%= button_to "Edit", edit_truck_icecream_path(@truck, @icecream), method: :get %>
    <%= button_to "Delete", truck_icecream_path(@truck, @icecream), method: :delete %>
<% end %>