config/routes.rb
Rails.application.routes.draw do
  
  root 'static#home'

  resources :trucks, except: [:new] do ### BLOG POST
    resources :icecreams
    resources :orders, only: [:new, :create, :index]
  end

  # New Truck
  get 'truck_signup', to: 'trucks#new'

  # New Customer
  get 'signup', to: 'customers#new'
  
  # Sessions
  get 'truck_login', to: "sessions#truck_login"
  post 'truck_login', to: 'sessions#create'
  get 'login', to: 'sessions#login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :customers, except: [:new] do
    resources :trucks, only: [:index]
    # Customer Wallet
    get 'wallet', to: 'customers#wallet'
    patch 'wallet', to: 'customers#update_wallet'
  end

  resources :orders, only: [:index]

  # Oauth Facebook
  get '/auth/facebook/callback', to: 'sessions#create_via_fb'

end

app/views/layouts/_customer_layout.html.erb
<%= link_to "My Account", customer_path(current_customer)%>
<%= link_to "Icecream Trucks", customer_trucks_path(current_customer)%>
<%= link_to "My Wallet", customer_wallet_path(current_customer) %>
<%= link_to "My Orders", orders_path%>
<%= link_to "Log Out", logout_path %>

app/views/layouts/_home_layout.html.erb
<%= link_to "Home", root_path %>
<%= link_to "Icecream Truck Owner Sign Up", truck_signup_path %>
<%= link_to "Icecream Truck Owner Log In", truck_login_path %>
<%= link_to "Customer Sign Up", signup_path %>
<%= link_to "Customer Log In", login_path %>

app/views/layouts/_truck_layout.html.erb
<%= link_to "Settings", edit_truck_path(current_truck) %>
<%= link_to "My Menu", truck_path(current_truck) %>
<%= link_to "Trucks In The Area", trucks_path %>
<%= link_to "Orders", truck_orders_path(current_truck) %>
<%= link_to "Log Out", logout_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IcyTruck</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="/stylesheets/main.css">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <% flash.each do |type, msg| %>
      <div class = "flash-error">
          <p><%= msg %></p>
      </div>
    <% end %>
    
    <nav>
      <div class="nav-bar">
      <% if session[:truck_id] %>
        <%= render 'layouts/truck_layout' %>
      <% elsif session[:customer_id] %>
        <%= render 'layouts/customer_layout' %>
      <% else %>
        <%= render 'layouts/home_layout' %>
      <% end %>
      </div>
    </nav>
    
    <div class="everything">
    <%= yield %>
    </div>
  
  </body>
</html>